description = "Create a commit message based on staged changes"

prompt = '''
Generate a commit message, listing and summarizing the main changes, based on the following git  diff:

```diff
!{git diff --staged}
```

Use emoji for types of changes:
- for style changes use ğŸ¨
- for bug fixes use ğŸ›
- for new features use ğŸ£
- for docs use ğŸ“„

'''
